
# Site settings
title: ISRAEL BIKERS
email: support@israel-bikers.com
description: >- 
  Motorcycles news and events from Israel and all over the world.
baseurl: ""
url: "http://israel-bikers.com"                           # github pages
#url: "http://www.israel-bikers.com"                      # github pages
#url: "https://shaharl.github.io/www.israel-bikers.com"   # github pages
#url: "http://127.0.0.1:4000" 
lang: "en"

# Build settings
markdown: kramdown
permalink: none
exclude:
  - Gemfile
  - Gemfile.lock

#theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
