
# Site settings
title: ISRAEL BIKERS
email: support@israel-bikers.com
description: >- 
  Motorcycles news and events from Israel and all over the world.
baseurl: "www.israel-bikers.com" # for github pages
#baseurl: "www.israel-bikers.com" # for github pages
url: "http://www.israel-bikers.com" 
lang: "en"

# Build settings
markdown: kramdown
permalink: none
exclude:
  - Gemfile
  - Gemfile.lock

#theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
